### ISSUE TITLE
How to use weak and strong "until"s in structuredslugs?

### ISSUE THREAD

**Issue by sguysc** [VerifiableRobotics/slugs#22] opened 2020-04-01 22:53 UTC
Cannot use the Structured slugs compiler tool, it seems like it might not support 
**BinaryTemporalFormula** formula when having a until operator in the formula.
I tried to make a minimum working example here:
```
[INPUT]
R:0...2
B

[OUTPUT]
M:0...1

[SYS_LIVENESS]
R=3
R=0

[SYS_INIT]
!(M=1)

[ENV_TRANS]
(R=0 & M=0)->((R=0)**W**(R=2))
(R=0 & M=1)->(R'=0)
(R=1 & M=0)->((R=1)**W**(R=2))
(R=1 &  M=1)->(R'=0)
(R=1 & M=0)->(R'=2)
(R=2 & M=1)->(R'=1)

[ENV_INIT]
R=0
!B

[SYS_TRANS]
(B')->(M'=1)

[ENV_LIVENESS]
!B
```
and get:
```
Cannot parse sub-tree!
['BinaryTemporalFormula', ['CalculationSubformula', ['numID', 'R'], ['NumberComparisonOperator', ['EqualOperator', ('=',)]], ['numeral', '0']], ['WeakUntilOperator', ('W',)], ['CalculationSubformula', ['numID', 'R'], ['NumberComparisonOperator', ['EqualOperator', ('=',)]], ['numeral', '2']]]
```
Is there a specific syntax for W, or is it not supported this way?

**Comment by progirep** [comment] 2020-04-02 08:15
Thanks for your request.

The slugs tool only supports Generalized Reactivity(1) specifications. In this specification form, the environment assumptions and system guarantees come from a subset of LTL. This subset of LTL is severely restricted and in particular does not support Until or Weak until subformulas.

The structured slugs parser uses a grammar for full LTL though (https://github.com/VerifiableRobotics/slugs/blob/master/tools/StructuredSlugsParser/grammar.wi), which is the cause for this non-insightful error message. I'll fix that. 

The specification that you wrote can be encoded into GR(1) form using additional atomic propositions. I've summarized the basic ideas of this process on pages 117-119 of my PhD thesis (https://www.ruediger-ehlers.de/papers/DissertationEhlers.pdf), as I were not aware of any proper explanation of this process in the literature before it was written, while the main ideas of such an encoding were already known to the community at that time.

As an example, in your specification, the line

    [ENV_TRANS]
    (R=0 & M=0)->((R=0)**W**(R=2))

can be written as:

    [OUTPUT]
    hp1

    [SYS_INIT]
    hp1 <-> (R=0 & M=0)

    [SYS_TRANS]
    hp1' <-> (hp1 & !(R'=2)) | (R'=0 & M'=0)

    [ENV_TRANS]
    hp1 -> (R=0 | R=2)

The idea is that the auxiliary proposition "hp1" that the system to be synthesized will set keeps track of whether the "((R=0)**W**(R=2))" property should currently hold.

Please let me know if you have further questions. I will close this question until then, but feel free to reopen it if the answer does not properly address your question. There is currently no automatic process for translating formulas of your kind to GR(1) specifications, as the efficiency of GR(1) synthesis depends a lot on how exactly this is done.

**Closed by progirep** 2020-04-02 08:15 UTC
